name: Build
on:
  push:
    branches:
    - main
jobs:
  cleaner:
    runs-on: self-hosted
    steps:
      - name: Clean up previous runs
        run: rm -rf "${{ github.workspace }}"

  build-docker-image:
    runs-on: self-hosted
    needs: cleaner
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    
    - name: Generate Docker image tag
      id: generate-tag
      run: |
        export TAG=sparsetir:$(date +%s)
        echo "tag=$TAG" >> $GITHUB_OUTPUT
    
    - name: Build Docker image
      run: |
        DOCKER_BUILDKIT=1 docker build \
          . \
          --file Dockerfile \
          --tag ${{ steps.generate-tag.outputs.tag }}

  run-tests:
    runs-on: self-hosted
    needs: build-docker-image
    steps:
    - name: Run tests
      id: run-tests
      run: docker run --gpus all ${{ needs.outputs.tag }} bash tests/scripts/task_python_sparsetir_unittest.sh

  build-doc:
    runs-on: self-hosted
    needs: build-docker-image
    steps:
    - name: Build Documentation
      id: build-doc
      run: |
        docker run ${{ needs.outputs.tag }} sphinx-build -b html docs/ public/
        docker cp ${{ needs.outputs.tag }}:public/ public/
  
  deploy-doc:
    runs-on: self-hosted
    needs: build-doc
    steps:
    - name: Deploy documentation
      id: deploy-doc
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: public
